[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-identity = "0.7.0"
argon2 = "0.5.3"
chrono = { version = "0.4.34", features = ["serde"] }
diesel = { version = "2.1.4", features = [
    "r2d2",
    "postgres",
    "chrono",
    "uuid",
] }
dotenv = "0.15.0"
jsonwebtoken = "9.0.2"
rand = "0.8.5"
serde = "1.0.196"
tokio = "1.36.0"
uuid = { version = "1.7.0", features = ["v4", "serde"] }
lettre = { version = "0.11.4", features = ["smtp-transport"] }
log = "0.4.21"
env_logger = "0.11.2"
thiserror = "1.0.57"

[features]
debug = []
