[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
argon2 = "0.5.3"
chrono = { version = "0.4.34", features = ["serde"] }
diesel = { version = "2.1.4", features = [
    "r2d2",
    "postgres",
    "chrono",
    "uuid",
] }
dotenv = "0.15.0"
jsonwebtoken = "9.0.2"
rand = "0.8.5"
serde = "1.0.196"
tokio = "1.36.0"
